# Generated by Django 4.2.2 on 2023-06-26 14:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("baseapplication", "0002_topic_room_host_message_room_topic"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="room",
            options={"ordering": ["-updated", "-created"]},
        ),
    ]
